### ISSUE TITLE
1st Issue - VRM not adding the yield 

### ISSUE THREAD

**Issue by NunoRgP** [mr-manuel/venus-os_dbus-mqtt-solar-charger#1]
Hello mr-manuel

I want to express my gratitude for the excellent work you've done. However, I've encountered a problem that I hope we can address. It appears that the VRM isn't considering the yield values from the driver when calculating the total solar production.

I've been utilizing the JSON minimum, which has been performing admirably. All values are displaying correctly in the VRM. Therefore, it's possible that the VRM is utilizing a different value for the total solar production of the day.

I noticed this after using the driver for a day and the solar production did not add up  .

Perhaps it might be necessary to incorporate additional requirements into the minimum specifications, such as the historical daily yield

Regards,

**Comment by mr-manuel** [comment]
Hello @NunoRgP,

the JSON minimum is related to have a working driver and system in Venus OS and not in showing all data in VRM. This is not needed.

Did you managed to get the yield into VRM? If yes can you exactly say which fields you have populated to see the yield in VRM? Then I would add this to the README.

**Comment by NunoRgP** [comment]
I would not say it is not needed , but it would be a nice to have for sure :) 

Not sure you understood me , on the picture bellow it is more clear . 

![VRM](https://github.com/mr-manuel/venus-os_dbus-mqtt-solar-charger/assets/3765598/32253199-e536-495a-9cf6-f5bedbed7cb3)

The driver shows up as a PV Charger correctly with all values showing up correctly, I did not do any modification I am only using the minimum Json : 

{
    "Pv": { "V": 60.0 },
    "Yield": { "Power": 120.0
    },
    "Dc": { "0": {"Current": 10.0, "Voltage": 12.0 }
    }
}

I checked the values that the Victron Shunt ( In Solar mode, ,it is the 3.2KW 150/80 solar charger  ) is sending to dbus and I am missing the DC Power : 

![DC0Power](https://github.com/mr-manuel/venus-os_dbus-mqtt-solar-charger/assets/3765598/16ab7bad-633f-4ce6-8d78-cfffcc0c23e6)

My guess is that this value is the one used to calculate the solar production on VRM .

I will try to see if I can modify the code to include the DC power to test my thesis , my programming skills are very rudimentary so it might take some time . Will update if it is successful

**Comment by NunoRgP** [comment]
Ok found it ... and it was not the DC power . 

It seems VRM is using the total Yield, which by default was 30 kwh and when I changed that value to 53kwh ( I fetch the value from the mppt )  the solar production on VRM jumped to 23 kwh . 

So mistery solved, to have the correct solar production the total yield value needs to be used . 

On your description you have User as the kwh produced until reset and system as the kwh produced until now ( lifetime) , but it is actually the other way around . 

User = kwh produced until now ( Value used by VRM )

system = kwh produced until reset 

![solved](https://github.com/mr-manuel/venus-os_dbus-mqtt-solar-charger/assets/3765598/e4d86971-a455-43d5-8cc7-7a065bedce93)

Hope it helps someone .
