### ISSUE TITLE
Gesamtertrag wird nicht angezeigt

### ISSUE THREAD

**Issue by gs-king1150** [mr-manuel/venus-os_dbus-mqtt-solar-charger#2]
bei mir wird der Gesamtertrag nicht angezeigt, 
hat jemand eine Idee?

![Screenshot 2024-04-22 201353](https://github.com/mr-manuel/venus-os_dbus-mqtt-solar-charger/assets/95379714/7112026c-c02c-4b74-8cd0-c0c36d692230)
![Screenshot 2024-04-22 200401](https://github.com/mr-manuel/venus-os_dbus-mqtt-solar-charger/assets/95379714/ee791948-8531-477b-9079-42829b8d4c7d)

**Comment by mr-manuel** [comment]
Try to add history - daily - 0 - yield. See full JSON.

**Comment by mr-manuel** [comment]
Ahhh, Yield - System should be the one to populate. If not try also Yield - User

**Comment by Freaksplace** [comment]
Kannst du mir mal deinen NodeRed flow einen Screen Shot machen? bin da auch gerade dran aus dem OpenDTU die MQTT in einen JSON zu überführen vielleicht finden den Fehler gemeinsam, ich bin aber noch am Anfang
